[package]
name = "stylus-context-provider"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "file-context-server-test"
path = "src/bin/context_server.rs" 

[dependencies]
anyhow = "1.0.95"
libruskel = "0.0.9"
libtenx = {path = "../tenx/crates/libtenx"}
mcp-sdk = {path = "../mcp-sdk"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mcp-client-rs = { git = "https://github.com/tim-schultz/mcp-client-rs.git" }
eng-assistant = { path = "../eng-assistant" }
log = "0.4.22"
env_logger = "0.11.4"
tokio = { version = "1.0", features = ["full"] }
regex = "1.10.3"
anthropic-sdk = { git = "https://github.com/tim-schultz/anthropic-sdk.git" }
alloy = { version = "0.9.2", features = ["full"] }
alloy-transport = "0.9.2"
url = "2.5.0"
dotenv = "0.15.0"
tracing-subscriber = "0.3"
tracing = "0.1"
home = "0.5.11"