use alloy::{
    contract::{ContractInstance, Interface},
    json_abi::JsonAbi,
    primitives::Address,
    providers::Provider,
};
use anyhow::{anyhow, Result};
use regex::Regex;
use serde_json::Value;

pub struct ContractInteraction {
    human_readable_abi: Value,
}

impl ContractInteraction {
    pub fn new(interface: String) -> Self {
        Self {
            human_readable_abi: Self::interface_to_human_readable(&interface).unwrap(),
        }
    }

    pub fn get_abi(&self) -> &Value {
        &self.human_readable_abi
    }

    /// Creates a contract instance from a contract address and JSON ABI.
    #[allow(dead_code)]
    pub fn build_contract<P: Provider>(
        address: Address,
        abi: Value,
        provider: P,
    ) -> Result<ContractInstance<Interface, P>> {
        let abi: JsonAbi = serde_json::from_value(abi).map_err(|e| anyhow!(e))?;
        let interface = Interface::new(abi);
        Ok(ContractInstance::new(address, provider, interface))
    }

    pub fn interface_to_human_readable(interface: &str) -> Result<Value> {
        let mut signatures = Vec::new();

        // Match function declarations
        let fn_regex = Regex::new(r"function\s+(\w+)\s*\((.*?)\)(?:\s+(?:external|public|private|internal))?\s*(?:(?:pure|view|payable))?\s*(?:returns\s*\((.*?)\))?").unwrap();

        // Match error declarations
        let error_regex = Regex::new(r"error\s+(\w+)\s*\((.*?)\)").unwrap();

        for line in interface.lines() {
            let line = line.trim();

            // Process function declarations
            if let Some(caps) = fn_regex.captures(line) {
                let name = caps.get(1).map_or("", |m| m.as_str());
                let inputs = caps.get(2).map_or("", |m| m.as_str());
                let outputs = caps.get(3).map_or("", |m| m.as_str());

                let mut signature = format!("function {}({})", name, Self::clean_params(inputs));

                if line.contains("view") {
                    signature.push_str(" view");
                } else if line.contains("pure") {
                    signature.push_str(" pure");
                }

                if !outputs.is_empty() {
                    signature.push_str(&format!(" returns ({})", Self::clean_params(outputs)));
                }

                signatures.push(signature);
            }

            // Process error declarations
            if let Some(caps) = error_regex.captures(line) {
                let name = caps.get(1).map_or("", |m| m.as_str());
                let params = caps.get(2).map_or("", |m| m.as_str());

                let signature = format!("error {}({})", name, Self::clean_params(params));
                signatures.push(signature);
            }
        }

        if signatures.is_empty() {
            return Err(anyhow!("No functions or errors found in interface"));
        }

        Ok(serde_json::Value::Array(
            signatures
                .into_iter()
                .map(serde_json::Value::String)
                .collect(),
        ))
    }

    fn clean_params(params: &str) -> String {
        params
            .split(',')
            .map(|p| {
                let parts: Vec<&str> = p.split_whitespace().collect();
                if parts.len() >= 2 {
                    format!("{} {}", parts[0], parts[1])
                } else {
                    p.trim().to_string()
                }
            })
            .collect::<Vec<String>>()
            .join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::providers::{Provider, RootProvider};
    use alloy::transports::BoxTransport;

    #[test]
    fn test_interface_to_human_readable() {
        let interface = r#"
            /**
             * This file was automatically generated by Stylus and represents a Rust program.
             * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
             */

            // SPDX-License-Identifier: MIT-OR-APACHE-2.0
            pragma solidity ^0.8.23;

            interface IEnglishAuction {
                function activePrompt() external view returns (string memory);

                function getImage(uint256 image_id) external view returns (string memory);

                function getImageOwner(address owner) external view returns (uint256);

                function aiSeller() external view returns (address);

                function endAt() external view returns (uint256);

                function started() external view returns (bool);

                function ended() external view returns (bool);

                function highestBidder() external view returns (address);

                function highestBid() external view returns (uint256);

                function bids(address bidder) external view returns (uint256);

                function initialize(uint256 starting_bid) external;

                function start() external;

                function bid(string calldata prompt) external payable;

                function imageGenerationStatus(uint256 token_id, bool active) external;

                function withdraw() external;

                function end() external;

                error AlreadyInitialized();

                error AlreadyStarted();

                error NotSeller();

                error AuctionEnded();

                error BidTooLow();

                error NotStarted();

                error NotEnded();

                error UnAuthorizedUpdate();
            }
        "#;

        let result = ContractInteraction::interface_to_human_readable(interface).unwrap();

        let signatures = result.as_array().unwrap();

        // Check total number of signatures
        assert_eq!(signatures.len(), 24);

        // Check specific signatures exist
        assert!(signatures
            .iter()
            .any(|s| s == "function activePrompt() view returns (string memory)"));
        assert!(signatures
            .iter()
            .any(|s| s == "function getImage(uint256 image_id) view returns (string memory)"));
        assert!(signatures.iter().any(|s| s == "error AlreadyInitialized()"));

        dbg!(&result);
    }

    #[test]
    fn test_interface_to_human_readable_empty() {
        let result = ContractInteraction::interface_to_human_readable("");
        assert!(result.is_err());
    }

    #[test]
    fn test_build_contract() {
        struct MockProvider;
        impl Provider for MockProvider {
            fn root(&self) -> &RootProvider<BoxTransport> {
                unimplemented!("This is just a mock")
            }
        }

        let address = Address::from_slice(&[0u8; 20]);
        let provider = MockProvider;

        let abi = serde_json::json!([
            {
                "inputs": [],
                "name": "activePrompt",
                "outputs": [{"type": "string"}],
                "stateMutability": "view",
                "type": "function"
            }
        ]);

        let result = ContractInteraction::build_contract(address, abi, provider);
        assert!(result.is_ok());
    }

    #[test]
    fn test_build_contract_invalid_abi() {
        struct MockProvider;
        impl Provider for MockProvider {
            fn root(&self) -> &RootProvider<BoxTransport> {
                unimplemented!("This is just a mock")
            }
        }

        let address = Address::from_slice(&[0u8; 20]);
        let provider = MockProvider;

        let invalid_abi = serde_json::json!("invalid");

        let result = ContractInteraction::build_contract(address, invalid_abi, provider);
        assert!(result.is_err());
    }
}
